# Google Colab Lab Assignment -Pretrained Modle

**Course Name:** [Deep Learning]

**Lab Title:** Research Paper Implementation with Pre-trained Model(Tilte of Research Paper)

**Student Name:**[Rohan Agrawal]

**Student ID:**[202201040208]

**Date of Submission:** [24/03/25]

**Group Members**: [Enter Names]

**Research Paper Study and Implementation**

**Instructions:**

1. Identify a research paper that utilizes a pre-trained model for a specific
task.

2. Study the methodology, dataset, and model used in the research paper.

3. Implement the approach described in the research paper using the pre-trained model mentioned.

4. Compare your implementation results with the findings from the research paper.


**Objective**
1.   Study a research paper utilizing a pre-trained model.
2.   Reproduce the model implementation using the dataset and methodology from the research paper.
3.   Fine-tune the pre-trained model and optimize hyperparameters.
3.   Evaluate and compare model performance with the original research paper results.









**Task 1: Research Paper Selection and Dataset Preparation (2 hours)**

**Instructions:**

1. Select a research paper that applies a pre-trained model (e.g., VGG, ResNet, EfficientNet, etc.).

2. Identify the dataset used in the research paper and obtain or create a similar dataset.(**Mention Dataset Link and Description**)

3. Perform necessary preprocessing steps:

 Resize images to match the model input dimensions.

 Apply data augmentation techniques if applicable.

4. Split the dataset into training, validation, and testing sets.

In [2]:
# Code of task1

**Task 2: Model Implementation and Fine-tuning**

**Instructions:**

1. Implement the pre-trained model as described in the research paper.

2. Visualize feature maps of few layers

3. Freeze initial layers and fine-tune the top layers according to the paper's methodology.

4. Optimize hyperparameters such as:

  Learning rate

  Batch size

  Number of epochs

  Optimizer choice (Adam, SGD, RMSprop, etc.)

4. Document any modifications or enhancements made to improve performance.

In [3]:
# code of Task 2

**Task 3: Model Evaluation and Performance Comparison**

**Instructions:**

1. Evaluate the trained model using performance metrics:

 Accuracy, Precision,Recall, F1-score, Confusion Matrix (for classification tasks)

2. Compare the results with those reported in the research paper.

3. Identify potential weaknesses and suggest improvements.
**Deliverables:**

Performance metrics summary (table or chart).

Graphs/plots showcasing model accuracy and loss trends.

Comparison with research paper results.

Discussion on model performance and areas for improvement.

In [4]:
##Code for Task 3

**Conclusion and Result Visulaization**

**Declaration**

I, Rohan Agrawal, confirm that the work submitted in this assignment is my own and has been completed following academic integrity guidelines. The code is uploaded on my GitHub repository account, and the repository link is provided below:

GitHub Repository Link: [Insert GitHub Link]

Signature: Rohan Agrawal

**Submission Checklist**

✔ Research paper details and summary

✔ Code file (Python Notebook or Script)

✔ Dataset or link to the dataset

✔ Visualizations (if applicable)

✔ Screenshots of model performance metrics

✔ Readme File

✔ Comparison with research paper results

In [5]:
!mkdir -p ~/.kaggle
!mv /content/kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json  # Secure the file


In [6]:
!kaggle datasets download -d alxmamaev/flowers-recognition
!unzip flowers-recognition.zip -d /content/dataset


Dataset URL: https://www.kaggle.com/datasets/alxmamaev/flowers-recognition
License(s): unknown
Archive:  flowers-recognition.zip
  inflating: /content/dataset/flowers/daisy/100080576_f52e8ee070_n.jpg  
  inflating: /content/dataset/flowers/daisy/10140303196_b88d3d6cec.jpg  
  inflating: /content/dataset/flowers/daisy/10172379554_b296050f82_n.jpg  
  inflating: /content/dataset/flowers/daisy/10172567486_2748826a8b.jpg  
  inflating: /content/dataset/flowers/daisy/10172636503_21bededa75_n.jpg  
  inflating: /content/dataset/flowers/daisy/102841525_bd6628ae3c.jpg  
  inflating: /content/dataset/flowers/daisy/10300722094_28fa978807_n.jpg  
  inflating: /content/dataset/flowers/daisy/1031799732_e7f4008c03.jpg  
  inflating: /content/dataset/flowers/daisy/10391248763_1d16681106_n.jpg  
  inflating: /content/dataset/flowers/daisy/10437754174_22ec990b77_m.jpg  
  inflating: /content/dataset/flowers/daisy/10437770546_8bb6f7bdd3_m.jpg  
  inflating: /content/dataset/flowers/daisy/10437929963_bc1

In [7]:
import os
import shutil
import numpy as np

# Define source and destination paths
src_folder = "/content/dataset/flowers"  # Current folder containing all categories
train_folder = "/content/dataset/train"
val_folder = "/content/dataset/val"
test_folder = "/content/dataset/test"

# Create directories if they don’t exist
for folder in [train_folder, val_folder, test_folder]:
    os.makedirs(folder, exist_ok=True)

# Split dataset into train (80%), val (10%), and test (10%)
for category in os.listdir(src_folder):
    category_path = os.path.join(src_folder, category)
    if os.path.isdir(category_path):  # Ensure it's a directory
        images = os.listdir(category_path)
        np.random.shuffle(images)

        train_split = int(0.8 * len(images))
        val_split = int(0.9 * len(images))

        for i, img in enumerate(images):
            src_img_path = os.path.join(category_path, img)

            if i < train_split:
                dest_folder = os.path.join(train_folder, category)
            elif i < val_split:
                dest_folder = os.path.join(val_folder, category)
            else:
                dest_folder = os.path.join(test_folder, category)

            os.makedirs(dest_folder, exist_ok=True)
            shutil.move(src_img_path, dest_folder)

print("Dataset organized into Train, Validation, and Test sets!")


Dataset organized into Train, Validation, and Test sets!


Task 1: Dataset Preparation

Dataset Description: The dataset contains 4,326 images of 5 flower categories.

In [8]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.vgg16 import preprocess_input

# Define paths
train_dir = '/content/dataset/train'
val_dir = '/content/dataset/val'
test_dir = '/content/dataset/test'

# Data Augmentation & Preprocessing
train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=20,
    horizontal_flip=True,
    width_shift_range=0.2,
    height_shift_range=0.2
)

val_test_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)

# Load datasets
batch_size = 32
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=batch_size,
    class_mode='categorical'
)

val_generator = val_test_datagen.flow_from_directory(
    val_dir,
    target_size=(224, 224),
    batch_size=batch_size,
    class_mode='categorical'
)

test_generator = val_test_datagen.flow_from_directory(
    test_dir,
    target_size=(224, 224),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=False
)

Found 3452 images belonging to 5 classes.
Found 430 images belonging to 5 classes.
Found 435 images belonging to 5 classes.


Task 2: Model Implementation and Fine-Tuning

In [9]:
from tensorflow.keras.applications import VGG16
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

# Load pre-trained VGG16
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False  # Freeze base layers

# Add custom layers
x = base_model.output
x = Flatten()(x)
x = Dense(1024, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(5, activation='softmax')(x)
model = Model(inputs=base_model.input, outputs=predictions)

# Compile and train top layers
model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(train_generator, epochs=10, validation_data=val_generator)

# Visualize feature maps (first convolutional layer)
layer_output = base_model.get_layer('block1_conv1').output
activation_model = Model(inputs=base_model.input, outputs=layer_output)
example_image = next(train_generator)[0][0]
activations = activation_model.predict(np.expand_dims(example_image, axis=0))

# Fine-tune last 4 convolutional blocks
base_model.trainable = True
for layer in base_model.layers[:15]:
    layer.trainable = False

model.compile(optimizer=SGD(learning_rate=0.0001, momentum=0.9), loss='categorical_crossentropy', metrics=['accuracy'])
history_fine = model.fit(train_generator, epochs=10, validation_data=val_generator)

/usr/local/lib/python3.11/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


Epoch 1/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 88s 666ms/step - accuracy: 0.6129 - loss: 28.3037 - val_accuracy: 0.8488 - val_loss: 2.0329
Epoch 2/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 55s 513ms/step - accuracy: 0.7612 - loss: 2.5172 - val_accuracy: 0.8442 - val_loss: 0.7250
Epoch 3/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 57s 526ms/step - accuracy: 0.7504 - loss: 0.9803 - val_accuracy: 0.8349 - val_loss: 0.8229
Epoch 4/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 56s 517ms/step - accuracy: 0.7948 - loss: 0.7341 - val_accuracy: 0.8488 - val_loss: 0.6013
Epoch 5/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 82s 514ms/step - accuracy: 0.7994 - loss: 0.7617 - val_accuracy: 0.8442 - val_loss: 0.6788
Epoch 6/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 54s 503ms/step - accuracy: 0.7950 - loss: 0.6634 - val_accuracy: 0.8628 - val_loss: 0.5941
Epoch 7/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 54s 502ms/step - accuracy: 0.8195 - loss: 0.5871 - val_accuracy: 0.8605 - val_loss: 0.7068
Epoch 8/10
108/108 ━━━━━━━━━━━━━━━━━━━━ 55s 506ms/step - accuracy: 0.8234 - loss: 

Task 3: Model Evaluation

In [13]:
from sklearn.metrics import classification_report, confusion_matrix

# Evaluate test set
test_loss, test_acc = model.evaluate(test_generator)
print(f'Test Accuracy: {test_acc * 100:.2f}%')

# Generate predictions
y_true = test_generator.classes
y_pred = np.argmax(model.predict(test_generator), axis=1)

# Performance metrics
print(classification_report(y_true, y_pred, target_names=list(test_generator.class_indices.keys())))
print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))

14/14 ━━━━━━━━━━━━━━━━━━━━ 3s 218ms/step - accuracy: 0.9256 - loss: 0.2722
Test Accuracy: 91.49%
14/14 ━━━━━━━━━━━━━━━━━━━━ 4s 257ms/step
              precision    recall  f1-score   support

       daisy       0.95      0.94      0.94        77
   dandelion       0.89      0.95      0.92       106
        rose       0.90      0.90      0.90        79
   sunflower       0.93      0.91      0.92        74
       tulip       0.92      0.88      0.90        99

    accuracy                           0.91       435
   macro avg       0.92      0.91      0.92       435
weighted avg       0.92      0.91      0.91       435

Confusion Matrix:
 [[ 72   3   1   0   1]
 [  3 101   1   0   1]
 [  1   1  71   2   4]
 [  0   5   0  67   2]
 [  0   3   6   3  87]]
